name: movie_search_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0
  http: ^1.2.0
  go_router: ^5.0.0
  flutter_svg: ^1.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  shared_preferences: ^2.0.0
  intl: ^0.17.0
  equatable: ^2.0.3
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/1.1.svg
    - assets/1.2.svg
    - assets/2.svg
    - assets/2.2.svg
    - assets/3.svg
    - assets/3.3.svg
    - assets/333.svg
    - assets/back.svg
    - assets/vector.svg